// SPDX-License-Identifier: MIT
//
// GENERATED FILE — DO NOT EDIT.
// Generated by scripts/gen_sim_pipeline.py from fpga/project/system_bd.tcl.
// Regenerate: python3 scripts/gen_sim_pipeline.py \
//     --bd fpga/project/system_bd.tcl --out-dir fpga/rtl
//
// The block design is the single source of truth for the pipeline wiring
// (DECISIONS.md D19). Simulation-only assigns and assertions live in
// scripts/pipeline_sim_view.py EXTRA.

`timescale 1ns/1ps
module rx_frontend (
    input wire clk,
    input wire rst_n,
    input wire iq_valid_in,
    input wire [11:0] iq_i_in,
    input wire [11:0] iq_q_in,
    input wire playback_start,
    input wire [15:0] stf_end_skip,
    input wire [15:0] ltf_skip,
    input wire [7:0] stf_threshold,
    output wire tag_valid,
    output wire [3:0] tag_rate,
    output wire [11:0] tag_length,
    output wire tag_fcs_ok,
    output wire frame_detect,
    output wire [24:0] frame_offset,
    output wire stf_end,
    output wire cfo_done,
    output wire [15:0] phase_inc,
    output wire seq_done,
    output wire signal_valid,
    output wire [3:0] parsed_rate,
    output wire [11:0] parsed_length,
    output wire [3:0] state,
    output wire fcs_valid,
    output wire fcs_fail,
    output wire tag_abort,
    output wire [7:0] diag_frames_found,
    output wire [7:0] diag_frames_rejected,
    output wire [15:0] diag_drop_cnt,
    output wire [15:0] diag_clip_cnt,
    output wire psdu_byte_valid,
    output wire [7:0] psdu_byte_out,
    output wire psdu_frame_done,
    output wire [11:0] psdu_byte_count
);

    // internal nets (names from scripts/pipeline_sim_view.py)
    wire acq_pipeline_ack;
    wire cfo_done_w;
    wire frame_detect_w;
    wire [15:0] phase_inc_w;
    wire stf_end_w;
    wire watchdog_reset_w;

    // Free-running sample counter models the DDR write pointer in the absence
    // of iq_dma_rx (rx_frontend.v:96-105 pre-inversion).
    reg [24:0] sim_ddr_wr_ptr;
    always @(posedge clk) begin
        if (!rst_n)
            sim_ddr_wr_ptr <= 0;
        else if (iq_valid_in)
            sim_ddr_wr_ptr <= sim_ddr_wr_ptr + 1;
    end

    stf_detect u_stf_detect (
        .clk(clk),
        .rst_n(rst_n),
        .enable(1'b1),
        .clear(watchdog_reset_w),
        .soft_clear(playback_start),
        .iq_valid(iq_valid_in),
        .iq_i(iq_i_in),
        .iq_q(iq_q_in),
        .threshold(stf_threshold),
        .pipeline_ack(acq_pipeline_ack),
        .frame_detect(frame_detect_w),
        .frame_offset(frame_offset),
        .stf_end(stf_end_w),
        .diag_out(),
        .diag_thresh()
    );

    cfo_est u_cfo_est (
        .clk(clk),
        .rst_n(rst_n),
        .start(frame_detect_w),
        .iq_i(iq_i_in),
        .iq_q(iq_q_in),
        .iq_valid(iq_valid_in),
        .done(cfo_done_w),
        .phase_inc(phase_inc_w)
    );

    rx_pipeline u_rx_pipeline (
        .clk(clk),
        .rst_n(rst_n),
        .frame_detect(frame_detect_w),
        .stf_end(stf_end_w),
        .stf_end_skip(stf_end_skip),
        .ltf_skip(ltf_skip),
        .iq_valid_in(iq_valid_in),
        .iq_re_in(iq_i_in),
        .iq_im_in(iq_q_in),
        .phase_inc_in(phase_inc_w),
        .cfo_done_in(cfo_done_w),
        .ddr_wr_ptr(sim_ddr_wr_ptr),
        .tag_valid(tag_valid),
        .tag_rate(tag_rate),
        .tag_length(tag_length),
        .tag_fcs_ok(tag_fcs_ok),
        .seq_done(seq_done),
        .signal_valid(signal_valid),
        .parsed_rate(parsed_rate),
        .parsed_length(parsed_length),
        .pipeline_ack(acq_pipeline_ack),
        .watchdog_reset(watchdog_reset_w),
        .state(state),
        .fcs_valid(fcs_valid),
        .fcs_fail(fcs_fail),
        .tag_abort(tag_abort),
        .diag_frames_found(diag_frames_found),
        .diag_frames_rejected(diag_frames_rejected),
        .diag_drop_cnt(diag_drop_cnt),
        .diag_clip_cnt(diag_clip_cnt),
        .psdu_byte_valid(psdu_byte_valid),
        .psdu_byte_out(psdu_byte_out),
        .psdu_frame_done(psdu_frame_done),
        .psdu_byte_count(psdu_byte_count)
    );

    assign frame_detect = frame_detect_w;
    assign stf_end      = stf_end_w;
    assign cfo_done     = cfo_done_w;
    assign phase_inc    = phase_inc_w;

endmodule
