// SPDX-License-Identifier: MIT
//
// GENERATED FILE — DO NOT EDIT.
// Generated by scripts/gen_sim_pipeline.py from fpga/project/system_bd.tcl.
// Regenerate: python3 scripts/gen_sim_pipeline.py \
//     --bd fpga/project/system_bd.tcl --out-dir fpga/rtl
//
// The block design is the single source of truth for the pipeline wiring
// (DECISIONS.md D19). Simulation-only assigns and assertions live in
// scripts/pipeline_sim_view.py EXTRA.

`timescale 1ns/1ps
module rx_pipeline (
    input wire clk,
    input wire rst_n,
    input wire frame_detect,
    input wire stf_end,
    input wire [15:0] stf_end_skip,
    input wire [15:0] ltf_skip,
    input wire iq_valid_in,
    input wire [11:0] iq_re_in,
    input wire [11:0] iq_im_in,
    input wire [15:0] phase_inc_in,
    input wire cfo_done_in,
    input wire [24:0] ddr_wr_ptr,
    output wire tag_valid,
    output wire [3:0] tag_rate,
    output wire [11:0] tag_length,
    output wire tag_fcs_ok,
    output wire seq_done,
    output wire signal_valid,
    output wire [3:0] parsed_rate,
    output wire [11:0] parsed_length,
    output wire pipeline_ack,
    output wire watchdog_reset,
    output wire cfo_start,
    output wire [3:0] state,
    output wire fcs_valid,
    output wire fcs_fail,
    output wire tag_abort,
    output wire [7:0] diag_frames_found,
    output wire [7:0] diag_frames_rejected,
    output wire [15:0] diag_drop_cnt,
    output wire [15:0] diag_clip_cnt,
    output wire [31:0] diag_abort_cnts,
    output wire [31:0] diag_abort_sig,
    output wire [31:0] diag_abort_ctx,
    output wire [31:0] diag_tag_sig,
    output wire [31:0] diag_tag_ctx,
    output wire psdu_byte_valid,
    output wire [7:0] psdu_byte_out,
    output wire psdu_frame_done,
    output wire [11:0] psdu_byte_count
);

    // internal nets (names from scripts/pipeline_sim_view.py)
    wire [1:0] code_rate_out;
    wire deint_done /* verilator public */;
    wire deint_valid;
    wire depunct_full /* verilator public */;
    wire depunct_valid;
    wire [15:0] eq_data_im;
    wire [15:0] eq_data_re;
    wire eq_data_valid;
    wire [15:0] eq_pilot_im;
    wire [15:0] eq_pilot_re;
    wire eq_pilot_valid;
    wire fcs_fail_w;
    wire fcs_valid_w;
    wire [5:0] fft_bin_idx;
    wire [15:0] fft_bin_im;
    wire [15:0] fft_bin_re;
    wire fft_bin_valid;
    wire [15:0] n_acquisition_ctrl_0_desc_ltf_pos;
    wire [15:0] n_acquisition_ctrl_0_desc_phase_inc;
    wire n_acquisition_ctrl_0_desc_valid;
    wire [11:0] n_cfo_mixer_0_iq_i_out;
    wire [11:0] n_cfo_mixer_0_iq_q_out;
    wire n_cfo_mixer_0_iq_valid_out;
    wire n_chan_est_0_done;
    wire [15:0] n_chan_est_0_h_inv_im;
    wire [15:0] n_chan_est_0_h_inv_re;
    wire [4:0] n_chan_est_0_shift_val;
    wire [5:0] n_decode_engine_0_ce_rd_addr;
    wire n_decode_engine_0_chan_est_start;
    wire n_decode_engine_0_corr_enable_out;
    wire [15:0] n_decode_engine_0_corr_sample_pos_out;
    wire n_decode_engine_0_depunct_restart;
    wire n_decode_engine_0_eq_start;
    wire n_decode_engine_0_fcs_frame_start;
    wire [15:0] n_decode_engine_0_fft_din_im_out;
    wire [15:0] n_decode_engine_0_fft_din_re_out;
    wire n_decode_engine_0_fft_din_valid_out;
    wire n_decode_engine_0_fft_rst_n_out;
    wire n_decode_engine_0_fifo_pop;
    wire n_decode_engine_0_is_signal_out;
    wire n_decode_engine_0_ltf_peak_ack;
    wire [15:0] n_decode_engine_0_norm_out;
    wire [11:0] n_decode_engine_0_psdu_len_out;
    wire [1:0] n_decode_engine_0_rate_mode_out;
    wire [7:0] n_decode_engine_0_symbol_idx_out;
    wire n_decode_engine_0_symbol_start_out;
    wire n_decode_engine_0_vit_flush;
    wire [7:0] n_deinterleaver_0_soft_out0;
    wire [7:0] n_deinterleaver_0_soft_out1;
    wire [15:0] n_demap_mux_0_im_out;
    wire [15:0] n_demap_mux_0_re_out;
    wire n_demap_mux_0_valid_out;
    wire [7:0] n_demapper_0_soft_wide0;
    wire [7:0] n_demapper_0_soft_wide1;
    wire [7:0] n_demapper_0_soft_wide2;
    wire [7:0] n_demapper_0_soft_wide3;
    wire [7:0] n_demapper_0_soft_wide4;
    wire [7:0] n_demapper_0_soft_wide5;
    wire n_demapper_0_wide_valid;
    wire [7:0] n_depuncturer_0_soft_out;
    wire n_descrambler_0_bit_out;
    wire n_descrambler_0_valid_out;
    wire [5:0] n_equalizer_0_data_idx;
    wire [1:0] n_equalizer_0_pilot_idx;
    wire [5:0] n_equalizer_0_rd_addr;
    wire n_equalizer_0_symbol_done;
    wire [5:0] n_fft64_sdf_0_dout_idx;
    wire [15:0] n_fft64_sdf_0_dout_im;
    wire [15:0] n_fft64_sdf_0_dout_re;
    wire n_fft64_sdf_0_dout_valid;
    wire n_frame_fifo_0_empty;
    wire n_frame_fifo_0_full;
    wire [15:0] n_frame_fifo_0_pop_ltf_pos;
    wire [15:0] n_frame_fifo_0_pop_phase_inc;
    wire [28:0] n_ltf_correlator_0_metric;
    wire n_ltf_correlator_0_metric_valid;
    wire n_ltf_peak_detect_0_peak_found;
    wire [28:0] n_ltf_peak_detect_0_peak_metric;
    wire [15:0] n_ltf_peak_detect_0_peak_sample_pos;
    wire [15:0] n_pilot_track_0_diag_atan2_x;
    wire [15:0] n_pilot_track_0_diag_atan2_y;
    wire [5:0] n_pilot_track_0_diag_data_count;
    wire [15:0] n_pilot_track_0_diag_phase_acc;
    wire [3:0] n_pilot_track_0_diag_pilot_received;
    wire [2:0] n_pilot_track_0_diag_state;
    wire [7:0] n_soft_pairer_0_soft0;
    wire [7:0] n_soft_pairer_0_soft1;
    wire n_vit_fifo_0_flush_out;
    wire n_vit_fifo_0_overflow;
    wire [7:0] n_vit_fifo_0_rd_soft0;
    wire [7:0] n_vit_fifo_0_rd_soft1;
    wire n_vit_fifo_0_rd_valid;
    wire n_viterbi_k7_0_bit_out;
    wire n_viterbi_k7_0_busy;
    wire pair_valid;
    wire [15:0] pt_data_im;
    wire [15:0] pt_data_re;
    wire pt_data_valid;
    wire [31:0] snap_data;
    wire snap_trig;
    wire snap_valid;
    wire vit_frame_start;
    wire vit_streaming_mode;
    wire vit_valid;
    wire vitf_full /* verilator public */;

    cfo_mixer u_cfo_mixer (
        .clk(clk),
        .rst_n(rst_n),
        .enable(1'd1),
        .phase_reset(1'd0),
        .phase_inc(phase_inc_in),
        .iq_valid_in(iq_valid_in),
        .iq_i_in(iq_re_in),
        .iq_q_in(iq_im_in),
        .iq_valid_out(n_cfo_mixer_0_iq_valid_out),
        .iq_i_out(n_cfo_mixer_0_iq_i_out),
        .iq_q_out(n_cfo_mixer_0_iq_q_out)
    );

    decode_engine u_decode_engine (
        .clk(clk),
        .rst_n(rst_n),
        .snap_mode(3'd0),
        .iq_valid_in(iq_valid_in),
        .iq_re_in(iq_re_in),
        .iq_im_in(iq_im_in),
        .fifo_empty(n_frame_fifo_0_empty),
        .pop_ltf_pos(n_frame_fifo_0_pop_ltf_pos),
        .pop_phase_inc(n_frame_fifo_0_pop_phase_inc),
        .fifo_pop(n_decode_engine_0_fifo_pop),
        .fft_din_valid_out(n_decode_engine_0_fft_din_valid_out),
        .fft_din_re_out(n_decode_engine_0_fft_din_re_out),
        .fft_din_im_out(n_decode_engine_0_fft_din_im_out),
        .fft_rst_n_out(n_decode_engine_0_fft_rst_n_out),
        .fft_dout_valid_in(n_fft64_sdf_0_dout_valid),
        .fft_dout_re_in(n_fft64_sdf_0_dout_re),
        .fft_dout_im_in(n_fft64_sdf_0_dout_im),
        .fft_dout_idx_in(n_fft64_sdf_0_dout_idx),
        .fft_bin_valid(fft_bin_valid),
        .fft_bin_idx(fft_bin_idx),
        .fft_bin_re(fft_bin_re),
        .fft_bin_im(fft_bin_im),
        .ltf_peak_found_in(n_ltf_peak_detect_0_peak_found),
        .ltf_peak_pos_in(n_ltf_peak_detect_0_peak_sample_pos),
        .ltf_peak_metric_in(n_ltf_peak_detect_0_peak_metric),
        .ltf_peak_ack(n_decode_engine_0_ltf_peak_ack),
        .corr_sample_pos_out(n_decode_engine_0_corr_sample_pos_out),
        .corr_enable_out(n_decode_engine_0_corr_enable_out),
        .chan_est_start(n_decode_engine_0_chan_est_start),
        .ce_rd_addr(n_decode_engine_0_ce_rd_addr),
        .ce_h_inv_re(n_chan_est_0_h_inv_re),
        .ce_h_inv_im(n_chan_est_0_h_inv_im),
        .chan_est_done(n_chan_est_0_done),
        .eq_start(n_decode_engine_0_eq_start),
        .eq_done(n_equalizer_0_symbol_done),
        .eq_rd_addr(n_equalizer_0_rd_addr),
        .eq_rd_sel(),
        .eq_data_valid(eq_data_valid),
        .eq_data_re(eq_data_re),
        .eq_data_im(eq_data_im),
        .eq_pilot_valid(eq_pilot_valid),
        .eq_pilot_re(eq_pilot_re),
        .eq_pilot_im(eq_pilot_im),
        .deint_done(deint_done),
        .depunct_valid(depunct_valid),
        .vit_frame_start(vit_frame_start),
        .vit_flush(n_decode_engine_0_vit_flush),
        .vit_streaming_mode(vit_streaming_mode),
        .vit_valid(vit_valid),
        .vit_bit(n_viterbi_k7_0_bit_out),
        .descr_valid(n_descrambler_0_valid_out),
        .descr_bit(n_descrambler_0_bit_out),
        .fcs_frame_start(n_decode_engine_0_fcs_frame_start),
        .fcs_valid_in(fcs_valid_w),
        .fcs_fail_in(fcs_fail_w),
        .rate_mode_out(n_decode_engine_0_rate_mode_out),
        .code_rate_out(code_rate_out),
        .depunct_restart(n_decode_engine_0_depunct_restart),
        .norm_out(n_decode_engine_0_norm_out),
        .psdu_len_out(n_decode_engine_0_psdu_len_out),
        .signal_valid(signal_valid),
        .parsed_rate(parsed_rate),
        .parsed_length(parsed_length),
        .ddr_wr_ptr(ddr_wr_ptr),
        .tag_valid(tag_valid),
        .tag_rate(tag_rate),
        .tag_length(tag_length),
        .tag_fcs_ok(tag_fcs_ok),
        .snap_valid(snap_valid),
        .snap_data(snap_data),
        .snap_trig(snap_trig),
        .diag_vit_valid(n_vit_fifo_0_rd_valid),
        .diag_vit_soft0(n_vit_fifo_0_rd_soft0),
        .diag_vit_soft1(n_vit_fifo_0_rd_soft1),
        .diag_vit_overflow(n_vit_fifo_0_overflow),
        .diag_phase_acc(n_pilot_track_0_diag_phase_acc),
        .diag_atan2_x(n_pilot_track_0_diag_atan2_x),
        .diag_atan2_y(n_pilot_track_0_diag_atan2_y),
        .diag_pt_state(n_pilot_track_0_diag_state),
        .diag_pt_pilot_received(n_pilot_track_0_diag_pilot_received),
        .diag_pt_data_count(n_pilot_track_0_diag_data_count),
        .seq_done(seq_done),
        .tag_abort(tag_abort),
        .watchdog_reset(watchdog_reset),
        .diag_drop_cnt(diag_drop_cnt),
        .diag_abort_cnts(diag_abort_cnts),
        .diag_abort_sig(diag_abort_sig),
        .diag_abort_ctx(diag_abort_ctx),
        .diag_tag_sig(diag_tag_sig),
        .diag_tag_ctx(diag_tag_ctx),
        .symbol_idx_out(n_decode_engine_0_symbol_idx_out),
        .symbol_start_out(n_decode_engine_0_symbol_start_out),
        .is_signal_out(n_decode_engine_0_is_signal_out)
    );

    acquisition_ctrl u_acquisition_ctrl (
        .clk(clk),
        .rst_n(rst_n),
        .frame_detect(frame_detect),
        .stf_end(stf_end),
        .corr_metric_valid(n_ltf_correlator_0_metric_valid),
        .corr_metric(n_ltf_correlator_0_metric),
        .wr_ptr(n_decode_engine_0_corr_sample_pos_out),
        .cfo_done(cfo_done_in),
        .phase_inc(phase_inc_in),
        .desc_valid(n_acquisition_ctrl_0_desc_valid),
        .desc_ltf_pos(n_acquisition_ctrl_0_desc_ltf_pos),
        .desc_phase_inc(n_acquisition_ctrl_0_desc_phase_inc),
        .fifo_full(n_frame_fifo_0_full),
        .pipeline_ack(pipeline_ack),
        .cfo_start(cfo_start),
        .diag_frames_found(diag_frames_found),
        .diag_frames_rejected(diag_frames_rejected)
    );

    frame_fifo u_frame_fifo (
        .clk(clk),
        .rst_n(rst_n),
        .flush(1'd0),
        .push(n_acquisition_ctrl_0_desc_valid),
        .push_ltf_pos(n_acquisition_ctrl_0_desc_ltf_pos),
        .push_phase_inc(n_acquisition_ctrl_0_desc_phase_inc),
        .pop(n_decode_engine_0_fifo_pop),
        .pop_ltf_pos(n_frame_fifo_0_pop_ltf_pos),
        .pop_phase_inc(n_frame_fifo_0_pop_phase_inc),
        .empty(n_frame_fifo_0_empty),
        .full(n_frame_fifo_0_full),
        .count()
    );

    fft64_sdf u_fft (
        .clk(clk),
        .rst_n(n_decode_engine_0_fft_rst_n_out),
        .gate_rst_n(n_decode_engine_0_fft_rst_n_out),
        .din_valid(n_decode_engine_0_fft_din_valid_out),
        .i_idx(6'd0),
        .din_re(n_decode_engine_0_fft_din_re_out),
        .din_im(n_decode_engine_0_fft_din_im_out),
        .dout_valid(n_fft64_sdf_0_dout_valid),
        .dout_re(n_fft64_sdf_0_dout_re),
        .dout_im(n_fft64_sdf_0_dout_im),
        .dout_idx(n_fft64_sdf_0_dout_idx)
    );

    ltf_correlator u_ltf_corr (
        .clk(clk),
        .rst_n(rst_n),
        .iq_valid(n_cfo_mixer_0_iq_valid_out),
        .iq_re(n_cfo_mixer_0_iq_i_out),
        .iq_im(n_cfo_mixer_0_iq_q_out),
        .metric_valid(n_ltf_correlator_0_metric_valid),
        .metric(n_ltf_correlator_0_metric)
    );

    ltf_peak_detect u_ltf_peak (
        .clk(clk),
        .rst_n(rst_n),
        .enable(n_decode_engine_0_corr_enable_out),
        .metric_valid(n_ltf_correlator_0_metric_valid),
        .metric(n_ltf_correlator_0_metric),
        .sample_pos(n_decode_engine_0_corr_sample_pos_out),
        .ack(n_decode_engine_0_ltf_peak_ack),
        .peak_found(n_ltf_peak_detect_0_peak_found),
        .peak_sample_pos(n_ltf_peak_detect_0_peak_sample_pos),
        .peak_metric(n_ltf_peak_detect_0_peak_metric)
    );

    chan_est u_chan_est (
        .clk(clk),
        .rst_n(rst_n),
        .start(n_decode_engine_0_chan_est_start),
        .bin_valid(fft_bin_valid),
        .bin_idx(fft_bin_idx),
        .bin_re(fft_bin_re),
        .bin_im(fft_bin_im),
        .rd_addr(n_decode_engine_0_ce_rd_addr),
        .h_inv_re(n_chan_est_0_h_inv_re),
        .h_inv_im(n_chan_est_0_h_inv_im),
        .shift_val(n_chan_est_0_shift_val),
        .done(n_chan_est_0_done),
        .clip_cnt(diag_clip_cnt)
    );

    equalizer u_equalizer (
        .clk(clk),
        .rst_n(rst_n),
        .start(n_decode_engine_0_eq_start),
        .shift_val(n_chan_est_0_shift_val),
        .fft_valid(fft_bin_valid),
        .fft_bin(fft_bin_idx),
        .fft_re(fft_bin_re),
        .fft_im(fft_bin_im),
        .hinv_re(n_chan_est_0_h_inv_re),
        .hinv_im(n_chan_est_0_h_inv_im),
        .rd_addr(n_equalizer_0_rd_addr),
        .data_valid(eq_data_valid),
        .data_re(eq_data_re),
        .data_im(eq_data_im),
        .data_idx(n_equalizer_0_data_idx),
        .pilot_valid(eq_pilot_valid),
        .pilot_re(eq_pilot_re),
        .pilot_im(eq_pilot_im),
        .pilot_idx(n_equalizer_0_pilot_idx),
        .symbol_done(n_equalizer_0_symbol_done)
    );

    pilot_track u_pilot_track (
        .clk(clk),
        .rst_n(rst_n),
        .symbol_idx(n_decode_engine_0_symbol_idx_out),
        .is_signal(n_decode_engine_0_is_signal_out),
        .symbol_start(n_decode_engine_0_symbol_start_out),
        .pilot_valid(eq_pilot_valid),
        .pilot_re(eq_pilot_re),
        .pilot_im(eq_pilot_im),
        .pilot_idx(n_equalizer_0_pilot_idx),
        .data_valid_in(eq_data_valid),
        .data_re_in(eq_data_re),
        .data_im_in(eq_data_im),
        .data_idx_in(n_equalizer_0_data_idx),
        .data_valid_out(pt_data_valid),
        .data_re_out(pt_data_re),
        .data_im_out(pt_data_im),
        .symbol_done(),
        .diag_phase_acc(n_pilot_track_0_diag_phase_acc),
        .diag_atan2_x(n_pilot_track_0_diag_atan2_x),
        .diag_atan2_y(n_pilot_track_0_diag_atan2_y),
        .diag_state(n_pilot_track_0_diag_state),
        .diag_pilot_received(n_pilot_track_0_diag_pilot_received),
        .diag_data_count(n_pilot_track_0_diag_data_count)
    );

    demap_mux u_demap_mux (
        .is_signal(n_decode_engine_0_is_signal_out),
        .eq_data_valid(eq_data_valid),
        .eq_data_re(eq_data_re),
        .eq_data_im(eq_data_im),
        .pt_data_valid(pt_data_valid),
        .pt_data_re(pt_data_re),
        .pt_data_im(pt_data_im),
        .valid_out(n_demap_mux_0_valid_out),
        .re_out(n_demap_mux_0_re_out),
        .im_out(n_demap_mux_0_im_out)
    );

    demapper u_demapper (
        .clk(clk),
        .rst_n(rst_n),
        .rate_mode(n_decode_engine_0_rate_mode_out),
        .norm(n_decode_engine_0_norm_out),
        .valid_in(n_demap_mux_0_valid_out),
        .sym_re(n_demap_mux_0_re_out),
        .sym_im(n_demap_mux_0_im_out),
        .wide_valid(n_demapper_0_wide_valid),
        .soft_wide0(n_demapper_0_soft_wide0),
        .soft_wide1(n_demapper_0_soft_wide1),
        .soft_wide2(n_demapper_0_soft_wide2),
        .soft_wide3(n_demapper_0_soft_wide3),
        .soft_wide4(n_demapper_0_soft_wide4),
        .soft_wide5(n_demapper_0_soft_wide5)
    );

    deinterleaver u_deinterleaver (
        .clk(clk),
        .rst_n(rst_n),
        .rate_mode(n_decode_engine_0_rate_mode_out),
        .stall_in(depunct_full),
        .valid_in(n_demapper_0_wide_valid),
        .soft_in0(n_demapper_0_soft_wide0),
        .soft_in1(n_demapper_0_soft_wide1),
        .soft_in2(n_demapper_0_soft_wide2),
        .soft_in3(n_demapper_0_soft_wide3),
        .soft_in4(n_demapper_0_soft_wide4),
        .soft_in5(n_demapper_0_soft_wide5),
        .valid_out(deint_valid),
        .soft_out0(n_deinterleaver_0_soft_out0),
        .soft_out1(n_deinterleaver_0_soft_out1),
        .deint_done(deint_done)
    );

    depuncturer u_depuncturer (
        .clk(clk),
        .rst_n(rst_n),
        .code_rate(code_rate_out),
        .symbol_start(n_decode_engine_0_depunct_restart),
        .stall_in(vitf_full),
        .valid_in(deint_valid),
        .soft_in0(n_deinterleaver_0_soft_out0),
        .soft_in1(n_deinterleaver_0_soft_out1),
        .valid_out(depunct_valid),
        .soft_out(n_depuncturer_0_soft_out),
        .fifo_full(depunct_full)
    );

    soft_pairer u_soft_pairer (
        .clk(clk),
        .rst_n(rst_n),
        .frame_start(vit_frame_start),
        .stall_in(vitf_full),
        .valid_in(depunct_valid),
        .soft_in(n_depuncturer_0_soft_out),
        .valid_out(pair_valid),
        .soft0(n_soft_pairer_0_soft0),
        .soft1(n_soft_pairer_0_soft1)
    );

    viterbi_k7 u_viterbi (
        .clk(clk),
        .rst_n(rst_n),
        .frame_start(vit_frame_start),
        .flush(n_vit_fifo_0_flush_out),
        .streaming_mode(vit_streaming_mode),
        .valid_in(n_vit_fifo_0_rd_valid),
        .soft0(n_vit_fifo_0_rd_soft0),
        .soft1(n_vit_fifo_0_rd_soft1),
        .valid_out(vit_valid),
        .bit_out(n_viterbi_k7_0_bit_out),
        .busy(n_viterbi_k7_0_busy)
    );

    vit_fifo u_vit_fifo (
        .clk(clk),
        .rst_n(rst_n),
        .frame_start(vit_frame_start),
        .wr_valid(pair_valid),
        .wr_soft0(n_soft_pairer_0_soft0),
        .wr_soft1(n_soft_pairer_0_soft1),
        .rd_valid(n_vit_fifo_0_rd_valid),
        .rd_soft0(n_vit_fifo_0_rd_soft0),
        .rd_soft1(n_vit_fifo_0_rd_soft1),
        .vit_busy(n_viterbi_k7_0_busy),
        .full(vitf_full),
        .flush_in(n_decode_engine_0_vit_flush),
        .flush_out(n_vit_fifo_0_flush_out),
        .overflow(n_vit_fifo_0_overflow)
    );

    descrambler u_descrambler (
        .clk(clk),
        .rst_n(rst_n),
        .frame_start(n_decode_engine_0_fcs_frame_start),
        .valid_in(vit_valid),
        .bit_in(n_viterbi_k7_0_bit_out),
        .valid_out(n_descrambler_0_valid_out),
        .bit_out(n_descrambler_0_bit_out),
        .seed_detected(),
        .seed_valid()
    );

    fcs_check u_fcs_check (
        .clk(clk),
        .rst_n(rst_n),
        .frame_start(n_decode_engine_0_fcs_frame_start),
        .psdu_len(n_decode_engine_0_psdu_len_out),
        .valid_in(n_descrambler_0_valid_out),
        .bit_in(n_descrambler_0_bit_out),
        .fcs_valid(fcs_valid_w),
        .fcs_fail(fcs_fail_w),
        .frame_done()
    );

    psdu_packer u_psdu_packer (
        .clk(clk),
        .rst_n(rst_n),
        .frame_start(n_decode_engine_0_fcs_frame_start),
        .psdu_len(n_decode_engine_0_psdu_len_out),
        .valid_in(n_descrambler_0_valid_out),
        .bit_in(n_descrambler_0_bit_out),
        .byte_valid(psdu_byte_valid),
        .byte_out(psdu_byte_out),
        .byte_count(psdu_byte_count),
        .active(),
        .done(),
        .frame_done(psdu_frame_done),
        .frame_start_out()
    );

    // 4-bit FSM state exported from decode_engine snap_data for tests
    // (rx_pipeline.v:393 pre-inversion).
    assign state = snap_data[30:27];

    // fcs_check outputs are read by decode_engine and exposed for tests.
    assign fcs_valid = fcs_valid_w;
    assign fcs_fail  = fcs_fail_w;

`ifdef SIM
    // Puncture-phase assertions (rx_pipeline.v:641-682 pre-inversion).
    always @(posedge clk) begin
        if (rst_n && depunct_valid && !vitf_full &&
            code_rate_out != 2'd0 && !u_soft_pairer.have_first &&
            u_depuncturer.emit_par !== 1'b0)
            $error("[rx_pipeline] PUNCTURE PHASE SLIP: soft_pairer latched an odd-parity coded bit as G0 at %0t; a bit was dropped or duplicated between depuncturer and soft_pairer", $time);
    end
    always @(posedge clk) begin
        if (rst_n && vit_frame_start && vit_streaming_mode &&
            u_depuncturer.pat_pos !== 3'd0)
            $error("[rx_pipeline] PUNCTURE PATTERN CARRYOVER: DATA phase started with pat_pos=%0d (expected 0) at %0t; the previous frame left the depuncturer mid-group",
                   u_depuncturer.pat_pos, $time);
    end
`endif

endmodule
