#!/usr/bin/env python3
"""gen_deint_enc.py — regenerate the deinterleaver perm ROM as (subcarrier,lane).

The streaming demapper (lever C) writes one wide word per subcarrier into a
48-entry buffer, so the deinterleaver gather must convert an arrival bit
position p into a (word, lane) pair. For output index k the arrival position
is perm[k]; the ROM entry is

    enc = (subcarrier << 3) | lane
        subcarrier = perm[k] // n_bpsc
        lane      = perm[k] %  n_bpsc

which fits the existing 9-bit ROM width (6-bit subcarrier 0-47, 3-bit lane
0-5). BPSK/QPSK/16-QAM reduce to shifts; 64-QAM (n_bpsc=6) does not, which is
why the lane is precomputed rather than decoded arithmetically.

Permutation source of truth: the PERM_* tables in
fpga/test/test_deinterleaver.py (from lib80211 interleaver.c). They are parsed
with `ast`, so there is one authoritative copy.

Usage:
    python3 scripts/gen_deint_enc.py            # rewrite deinterleaver.v
    python3 scripts/gen_deint_enc.py --check    # exit 1 if it would change
"""

import argparse
import ast
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TEST = ROOT / "fpga/test/test_deinterleaver.py"
RTL = ROOT / "fpga/rtl/deinterleaver.v"

# (perm table name, n_bpsc, rom segment offset). Offsets/lengths must match the
# existing rom_base values in deinterleaver.v: 0/48/144/336, lengths 48/96/192/288.
SEGMENTS = [
    ("PERM_48", 1, 0),
    ("PERM_96", 2, 48),
    ("PERM_192", 4, 144),
    ("PERM_288", 6, 336),
]
ROM_SIZE = 624


def load_perms():
    tree = ast.parse(TEST.read_text())
    found = {}
    for node in tree.body:
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id.startswith("PERM_"):
                    found[target.id] = ast.literal_eval(node.value)
    missing = [name for name, _, _ in SEGMENTS if name not in found]
    if missing:
        sys.exit(f"could not find {missing} in {TEST}")
    return found


def enc_values(perms):
    rom = [0] * ROM_SIZE
    for name, n_bpsc, base in SEGMENTS:
        perm = perms[name]
        for k, p in enumerate(perm):
            rom[base + k] = ((p // n_bpsc) << 3) | (p % n_bpsc)
    return rom


def render(rom):
    lines = ["        // (subcarrier << 3) | lane, generated by scripts/gen_deint_enc.py"]
    for i in range(0, ROM_SIZE, 8):
        row = " ".join(f"perm_rom[{j}]=9'd{rom[j]};" for j in range(i, i + 8))
        lines.append("        " + row)
    return "\n".join(lines)


def patch(text, block):
    pattern = re.compile(r"(initial begin : perm_rom_init\n)(.*?)(\n    end)",
                         re.DOTALL)
    match = pattern.search(text)
    if not match:
        sys.exit("perm_rom_init block not found in deinterleaver.v")
    return text[:match.start(2)] + "\n" + block + text[match.end(2):]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if deinterleaver.v is stale")
    args = parser.parse_args()

    block = render(enc_values(load_perms()))
    old = RTL.read_text()
    new = patch(old, block)

    if args.check:
        if new != old:
            sys.exit("deinterleaver.v perm_rom is stale — run gen_deint_enc.py")
        print("deinterleaver perm_rom up to date")
        return

    RTL.write_text(new)
    print(f"rewrote {RTL} perm_rom ({ROM_SIZE} entries)")


if __name__ == "__main__":
    main()
