#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# gen_sim_pipeline.py — generate the simulation view of the receiver pipeline
# (fpga/rtl/rx_pipeline.v, fpga/rtl/rx_frontend.v) from the block design
# (fpga/project/system_bd.tcl). The BD is the single authored source of truth
# for the pipeline wiring; see DECISIONS.md D19.
#
# Usage:
#   python3 scripts/gen_sim_pipeline.py --bd fpga/project/system_bd.tcl \
#       --out-dir fpga/rtl
#   python3 scripts/gen_sim_pipeline.py --check ...   # exit 1 if stale
#
# Port directions/widths come from Verilator XML elaborated over
# fpga/test/Makefile RX_FRONTEND_SRCS.

import argparse
import os
import subprocess
import sys
import tempfile
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from bd_graph import parse_bd, const_values  # noqa: E402
from verilog_ports import module_ports  # noqa: E402
import pipeline_sim_view as spec  # noqa: E402

BANNER = (
    "// SPDX-License-Identifier: MIT\n"
    "//\n"
    "// GENERATED FILE — DO NOT EDIT.\n"
    "// Generated by scripts/gen_sim_pipeline.py from fpga/project/system_bd.tcl.\n"
    "// Regenerate: python3 scripts/gen_sim_pipeline.py \\\n"
    "//     --bd fpga/project/system_bd.tcl --out-dir fpga/rtl\n"
    "//\n"
    "// The block design is the single source of truth for the pipeline wiring\n"
    "// (DECISIONS.md D19). Simulation-only assigns and assertions live in\n"
    "// scripts/pipeline_sim_view.py EXTRA.\n\n"
    "`timescale 1ns/1ps\n"
)


def elaborate(test_dir, tmp):
    """Elaborate RX_FRONTEND_SRCS to XML; return the XML path."""
    srcs = subprocess.run(
        ["make", "-s", "-C", test_dir, "print_rx_frontend_srcs"],
        capture_output=True, text=True, check=True).stdout.split()
    r = subprocess.run(
        ["verilator", "--xml-only", "--top-module", "rx_frontend",
         "--Mdir", tmp, "-Wno-DECLFILENAME", "-Wno-UNUSED", "-Wno-MULTITOP",
         "-Wno-PINCONNECTEMPTY", "-Wno-ASCRANGE", "-Wno-SYNCASYNCNET",
         "-Wno-fatal", *srcs], capture_output=True, text=True)
    if r.returncode != 0:
        sys.stderr.write(r.stdout + r.stderr)
        raise SystemExit("verilator elaboration failed")
    return os.path.join(tmp, "Vrx_frontend.xml")


def _find(parent, x):
    while parent.setdefault(x, x) != x:
        parent[x] = parent[parent[x]]
        x = parent[x]
    return x


def _union(parent, a, b):
    ra, rb = _find(parent, a), _find(parent, b)
    if ra != rb:
        parent[ra] = rb


def _verilog_width(w):
    return f"[{w - 1}:0] " if w > 1 else ""


def build_module(name, module_ports_map, cells_mod, edges, consts, child=None):
    """Return (verilog text) for one generated wrapper."""
    group = set(spec.CELLS[name])
    ep_edges = defaultdict(list)
    for a, b in edges:
        ep_edges[a].append(b)
        ep_edges[b].append(a)

    def mports(ep):
        return module_ports_map[cells_mod[ep[0]]]

    # --- union-find internal nets -------------------------------------------
    parent = {}
    for c in group:
        for p in mports((c, None)):
            _find(parent, (c, p))
    for a, b in edges:
        if a[0] in group and b[0] in group:
            _union(parent, a, b)

    comps = defaultdict(set)
    for ep in list(parent):
        comps[_find(parent, ep)].add(ep)

    net_name = {}
    wires = {}
    for members in comps.values():
        if len(members) < 2:
            continue  # singleton endpoints only become nets via BOUNDARY
        outs = [e for e in members if mports(e)[e[1]].dir == "output"]
        if len(outs) != 1:
            raise SystemExit(f"{name}: multi-driver net among {sorted(members)}")
        drv = outs[0]
        nm = spec.NET_NAMES.get(drv, f"n_{drv[0]}_{drv[1]}")
        for e in members:
            net_name[e] = nm
        wires[nm] = mports(drv)[drv[1]].width

    # boundary nets (single-endpoint named wires)
    for ep, res in {**spec.BOUNDARY.get(name, {}), **spec.SIM_EDGES.get(name, {})}.items():
        if res[0] == "net":
            wires.setdefault(res[1], mports(ep)[ep[1]].width)
            net_name.setdefault(ep, res[1])

    def resolve(ep):
        for table in (spec.SIM_EDGES.get(name, {}), spec.BOUNDARY.get(name, {})):
            if ep in table:
                return table[ep]
        others = ep_edges.get(ep, [])
        if any(o[0] in group for o in others):
            return ("net", net_name[ep])
        for o in others:
            if o[0] in spec.CLK_PORTS:
                return ("port", spec.CLK_PORTS[o[0]])
        for o in others:
            if o[0] in consts:
                w, v = consts[o[0]]
                return ("lit", f"{w}'d{v}")
        return ("unconn", None)

    # --- emit ---------------------------------------------------------------
    lines = [BANNER, f"module {name} (\n"]
    port_lines = []
    for pname, pdir, pwidth in spec.PORTS[name]:
        port_lines.append(f"    {pdir} wire {_verilog_width(pwidth)}{pname}")
    lines.append(",\n".join(port_lines))
    lines.append("\n);\n")

    if wires:
        lines.append("\n    // internal nets (names from scripts/pipeline_sim_view.py)\n")
        for nm, w in sorted(wires.items()):
            pub = " /* verilator public */" if nm in spec.PUBLIC else ""
            lines.append(f"    wire {_verilog_width(w)}{nm}{pub};\n")

    lines.append(spec.EXTRA_DECL[name])

    for cell in spec.CELLS[name]:
        mod = cells_mod[cell]
        inst = spec.INST_NAMES[cell]
        lines.append(f"\n    {mod} {inst} (\n")
        conns = []
        for pname in mports((cell, None)):
            res = resolve((cell, pname))
            if res[0] == "unconn":
                conns.append(f"        .{pname}()")
                continue
            expr = res[1]
            conns.append(f"        .{pname}({expr})")
        lines.append(",\n".join(conns))
        lines.append("\n    );\n")

    if child is not None:
        child_ports = {p: d for p, d, _w in spec.PORTS[child]}
        fe_ports = {p for p, _d, _w in spec.PORTS[name]}
        lines.append(f"\n    {child} u_{child} (\n")
        conns = []
        for pname, _d, _w in spec.PORTS[child]:
            if pname in spec.CHILD_CONN:
                expr = spec.CHILD_CONN[pname]
            elif pname in fe_ports:
                expr = pname
            else:
                raise SystemExit(f"{name}: no child connection for {child}.{pname}")
            conns.append(f"        .{pname}({expr})")
        lines.append(",\n".join(conns))
        lines.append("\n    );\n")

    lines.append(spec.EXTRA_BODY[name])
    lines.append("\nendmodule\n")
    return "".join(lines)


def generate(bd_path, xml_path):
    cells_mod, edges = parse_bd(bd_path)
    consts = const_values(open(bd_path).read())
    mpm = module_ports(xml_path)
    out = {}
    out["rx_pipeline"] = build_module("rx_pipeline", mpm, cells_mod, edges, consts)
    out["rx_frontend"] = build_module(
        "rx_frontend", mpm, cells_mod, edges, consts, child="rx_pipeline")
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--bd", required=True)
    ap.add_argument("--out-dir", required=True)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--test-dir",
                    default=os.path.join(HERE, "..", "fpga", "test"))
    args = ap.parse_args()

    with tempfile.TemporaryDirectory(prefix="gen_sim_pipeline.") as tmp:
        xml = elaborate(args.test_dir, tmp)
        files = generate(args.bd, xml)

    rc = 0
    for name, text in files.items():
        path = os.path.join(args.out_dir, f"{name}.v")
        if args.check:
            if not os.path.exists(path) or open(path).read() != text:
                sys.stderr.write(
                    f"STALE: {path} differs from the block-design-derived view.\n"
                    f"Regenerate: python3 scripts/gen_sim_pipeline.py "
                    f"--bd {args.bd} --out-dir {args.out_dir}\n")
                rc = 1
        else:
            with open(path, "w") as f:
                f.write(text)
            print(f"wrote {path}")
    return rc


if __name__ == "__main__":
    sys.exit(main())
